### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by combs** [stylight/python-wordpress-json#11]
Would be a nice upgrade :) 

Thanks,
Chris

**Comment by droustchev** [comment]
Hey @combs, OAuth would indeed be nice. As far as I know, WordPress does still not support this natively. I am not sure how feasible it would be do integrate a generic solution that would work with the plugins that add OAuth support to Wordpress, as I haven't looked into any of them. Do you happen to know how many different OAuth plugins there are and which are some of the most popular ones?

**Comment by combs** [comment]
Cool, that makes sense to me. I don't know much about it myself. I will let you know what I find out. Thank you!
