### ISSUE TITLE
Force deletion of posts?

### ISSUE THREAD

**Issue by treyturner** [stylight/python-wordpress-json#18]
Hi and thanks for this wrapper. Is it possible to force deletion of posts (skip the trash can) using this module? The Wordpress API supports it (https://developer.wordpress.org/rest-api/reference/posts/#delete-a-post), but it's not apparent to me how I would call your wrapper to achieve this.

**Comment by droustchev** [comment]
@treyturner, I haven't used the Wordpress API (and our wrapper) in a while and can't currently try it out, but you could try:
```python
from wordpress_json import WordpressJsonWrapper
wp = WordpressJsonWrapper('http://example.com/wp-json/wp/v2', 'wp_user', 'wp_password')
wp.delete_post(post_id=42, params={'force': 1})   
```
I couldn't tell from the WP documentation what force needs to be set to, but any true value should do it. Let me know if that helped.
